
#ifndef VG_MAX_PREREQUISITE_H_INCLUDED_
#define VG_MAX_PREREQUISITE_H_INCLUDED_

// 导出选项
enum	E_Export_Option
{
	FILTER_SELECTED		= SCENE_EXPORT_SELECTED,
	PROMPT_SETTING		= SCENE_EXPORT_SELECTED << 1,
	PROMPT_RESULT		= SCENE_EXPORT_SELECTED << 2,
	PROMPT_WARNING		= SCENE_EXPORT_SELECTED << 3,
	EXPORT_OPTION_COUNT
};

#define CLASS_ID_MOD_MAXPLUGIN_JPG_DEBUG	Class_ID(0x934305c, 0x5d4b0c7c);//vgMaxPlugin(Debug)
#define CLASS_ID_MOD_MAXPLUGIN_JPG_RELEASE	Class_ID(0x5967053d, 0x6bd52070);//vgMaxPlugin(Release)

#endif//VG_MAX_PREREQUISITE_H_INCLUDED_