


#ifndef __VGKSINGLETONLIFETIMEDEFINE_H__
#define __VGKSINGLETONLIFETIMEDEFINE_H__


#define VGK_SINGLETON_LEFE_COMMANDMGR			33

#define VGK_SINGLETON_LEFE_INPUTSYSTEM			50

#define VGK_SINGLETON_LEFE_GLOBALFACADE			100
#define VGK_SINGLETON_LEFE_MANIPULATEMGR		200

#define VGK_SIGNLETON_LEFE_ENTRYMGR				210
#define VGK_SIGNLETON_LEFE_GUIMGR				220
#define VGK_SIGNLETON_LEFE_UICONTROLMGR			221

#define VGK_SINGLETON_LEFE_VGMANAGER			250
#define VGK_SINGLETON_LEFE_MODMISCMANAGER		251


#define VGK_SINGLETON_LEFE_VMDANAGER			300
#define VGK_SINGLETON_LEFE_MODMANAGER			301

#define  VGK_SINGLETON_LEFE_XMLCONFIGMGR        302

#define VGK_SINGLETON_LEFE_MODELMANAGER			400

#define VGK_SIGLETON_LEFE_DLL_DECODER3DS		450

#define VGK_SINGLETON_LEFE_MESHMANAGER			500
#define VGK_SINGLETON_LEFE_OCCMANAGER			501
#define VGK_SINGLETON_LEFE_TIMELINEMANAGER      502
#define VGK_SINGLETON_LEFE_AUTOBUILDMANAGER     510
#define VGK_SINGLETON_LEFE_VECTORMANAGER		511
#define VGK_SIGLETON_LEFE_PROFILEMANAGER		512
#define VGK_SIGLETON_LEFE_DATABASEMANAGER		513


#define VGK_SIGLETON_LEFE_LOGOMANAGER			514

#define VGK_SINGLETON_LEFE_COORDSYS				515

#define VGK_SIGLETON_LEFE_DLLMANAGER			516
#define	VGK_SIGLETON_LEFE_MANAGERROOT			517

#define  VGK_SIGLETON_LEFE_PROGRAMNAME		518

#define VGK_SINGLETON_LEFE_TERRAINMGR			800
#define VGK_SINGLETON_LEFE_MODTERRAINMGR		810
#define VGK_SINGLETON_LEFE_TERRAINCENTERMGR		850
#define VGK_SINGLETON_LEFE_ELEVATIONMGR			860
#define VGK_SINGLETON_LEFE_ELEVATIONFILTER		870

#define VGK_SIGLETON_LEFE_GISDATAMGR			875
#define VGK_SINGLETON_LEFE_SHAPEMGR				880
#define VGK_SIGLETON_LEFE_AUTOPLANMANAGER		890

#define VGK_SINGLETON_LEFE_GPUMGR				900
#define VGK_SINGLETON_LEFE_TEXMGR				1000
#define VGK_SINGLETON_LEFE_IMAGEMGR				1500
#define VGK_SINGLETON_LEFE_CAMMGR				1550

#define VGK_SINGLETON_LEFE_CHANNEL				1555	

#define VGK_SINGLETON_LEFE_OCEAN				1556

#define VGK_SINGLETON_LEFE_COUTOUR				1557

#define VGK_SINGLETON_LEFE_RENDERERMGR			1560

#define VGK_SIGLETON_LEFE_SOUNDMANAGER			1561

#define VGK_SINGLETON_LEFE_RENDERERHOLDERMGR	1565

#define VGK_SINGLETON_LEFE_SOLARMGR				1566

#define VGK_SINGLETON_LEFE_TRIGGER				1567



#define VGK_SINGLETON_LEFE_GIS3D				1570
#define VGK_SINGLETON_LEFE_GISCOUR				1571

#define VGK_SINGLETON_LEFE_FONT					1575


#define VGK_SINGLETON_LEFE_CAUSTICS				1558
#define VGK_SINGLETON_LEFE_VI_BGMGR				1580
#define VGK_SINGLETON_LEFE_VI_FOGMGR			1581

#define VGK_SINGLETON_LEFE_TEXIODISPATCHER		1600
#define VGK_SINGLETON_LEFE_MAINTHREADMGR		1700
#define VGK_SINGLETON_LEFE_IOSERVER				2000

#define VGK_SINGLETON_LEFE_TRIGGER_EXT			2002

#define VGK_SINGLETON_LEFE_CAMMGRHOLDER			2500
#define VGK_SIGNLETON_LEFE_PYHSMANAGER			2600



#define VGK_SINGLETON_LEFE_SELECTMANAGER		2700

#define VGK_SINGLETON_LEFE_EDITCOPY_MANAGER		2701

// config singletons
#define VGK_SINGLETON_LEFE_VGCO_PROJMGR			3100
#define VGK_SINGLETON_LEFE_VGCO_EXEMGR			3105

#define VGK_SINGLETON_LEFE_GLOBALCONSOLE		4000

#define VGK_SINGLETON_LEFE_CACHEMGR				5000

#define VGK_SINGLETON_LEFE_SCRIPTMGR			6000

#define VGK_SINGLETON_LEFE_MEMORYFILEMGR		7000

#define VGK_SINGLETON_LEFE_SERIALIZERMGR		8000

#define VGK_SINGLETON_LEFE_PLUGINMGR			8500

#define VGK_SINGLETON_LEFE_CLASSFACTORYMGR		9000

#define VGK_SINGLETON_LEFE_ABSTREEFACMGR		9500

#define VGK_SINGLETON_LEFE_RENDERCOMMANDMGR		9535

#define VGK_SINGLETON_LEFE_PROPERTYMGR			9600

#define VGK_SINGLETON_LEFE_LOGMANAGER			10000

#define VGK_SINGLETON_LEFE_EXPORTMANAGER	    10400

#endif // end of __VGKSINGLETONLIFETIMEDEFINE_H__