


#ifndef __VGENTRYTYPE_H__
#define __VGENTRYTYPE_H__

//#include <vgKernel/vgkForward.h>

	

//enum vgEntryType
//{
//	VG_ENTRY_ROOT ,
//	VG_ENTRY_CAMMGR,
//	VG_ENTRY_MESH,
//	VG_ENTRY_MODOBJECT,
//	VG_ENTRY_VIEWCAM,
//	VG_ENTRY_PARTICLE,
//	VG_ENTRY_3DSOUND,
//	VG_ENTRY_BACKSOUND,
//	VG_ENTRY_MOVING,
//	VG_ENTRY_MS3D,
//	VG_ENTRY_VCR,
//	VG_ENTRY_TERRAIN,
//	VG_ENTRY_GISMATCH,
//	VG_ENTRY_VECSTRING,
//
//	VG_ENTRY_2DLAYER,
//	VG_ENTRY_2DGEOMETRY,
//
//	VG_ENTRY_BACKGROUND,
//	VG_ENTRY_FOG,
//
//	VG_ENTRY_SHAPE_LAYER,
//	VG_ENTRY_SHAPE_DATASOURCE
//};

	


#endif // end of __VGENTRYTYPE_H__